/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2018-08-17 11:37:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberEnroll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/views/member/../../end.jsp", Long.valueOf(1534417878888L));
    _jspx_dependants.put("/views/member/../../head.jsp", Long.valueOf(1534489056336L));
    _jspx_dependants.put("/views/member/../../footer.jsp", Long.valueOf(1534236327074L));
    _jspx_dependants.put("/views/member/../../header.jsp", Long.valueOf(1534501856383L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

	String mName = (String)session.getAttribute("m_Name");
	String mId = (String)session.getAttribute("m_Id");
	String mPassword = (String)session.getAttribute("m_password");


      out.write("\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"description\" content=\"GARO is a real-estate template\">\r\n");
      out.write("<meta name=\"author\" content=\"Kimarotec\">\r\n");
      out.write("<meta name=\"keyword\" content=\"html5, css, bootstrap, property, real-estate theme , bootstrap template\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("<link rel=\"icon\" href=\"favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/normalize.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/fontello.css\">\r\n");
      out.write("<link href=\"/semi/resources/fonts/icon-7-stroke/css/pe-icon-7-stroke.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/semi/resources/fonts/icon-7-stroke/css/helper.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/semi/resources/css/animate.css\" rel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/bootstrap-select.min.css\"> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/icheck.min_all.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/price-range.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/owl.carousel.css\">  \r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/owl.theme.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/owl.transitions.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/responsive.css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/semi/resources/js/jquery/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<title>09빌려줘</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 바디까지!! -->");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#btnLogin\").click(function(){\r\n");
      out.write("\t\t\t\t\tvar mid = $(\"#mid\").val();\r\n");
      out.write("\t\t\t\t\tvar mpassword = $(\"#mpassword\").val();\r\n");
      out.write("\t\t\t\t\tvar exp = /[a-z0-9]$/;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(mid == \"\"){\r\n");
      out.write("\t\t\t\t\t\talert(\"아이디를 입력해주세요\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#mid\").focus();\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(!exp.test(mid)){\r\n");
      out.write("\t\t\t\t\t\talert(\"영문자와 숫자만 입력가능합니다.\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#mid\").focus();\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t    if (mpassword == \"\") {\r\n");
      out.write("\t\t                alert(\"비밀번호를 입력해주세요\");\r\n");
      out.write("\t\t                $(\"#mpassword\").focus();\r\n");
      out.write("\t\t                return;\r\n");
      out.write("\t\t            }\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction goPage(){\r\n");
      out.write("\t\t\t\tlocation.href = \"/semi/adminIndex.jsp\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("        <style type=\"text/css\">\r\n");
      out.write("        input::placeholder {\r\n");
      out.write("  \t\t\tcolor: #aaaaaa;\r\n");
      out.write("\t\t\tfont-size : 10px;\r\n");
      out.write("\t\t}\r\n");
      out.write("        </style>\r\n");
      out.write("        <!-- Body content -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"header-connect\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-5 col-sm-8  col-xs-12\">\r\n");
      out.write("                        <div class=\"header-half header-call\">\r\n");
      out.write("                            <p>\r\n");
      out.write("                                <span><i class=\"pe-7s-call\"></i> 010-1234-5678</span>\r\n");
      out.write("                                <span><i class=\"pe-7s-mail\"></i> hongildong@iei\t.org</span>\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-2 col-md-offset-5  col-sm-3 col-sm-offset-1  col-xs-12\">\r\n");
      out.write("                        <div class=\"header-half header-social\">\r\n");
      out.write("                            <ul class=\"list-inline\">\r\n");
      out.write("                             \r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>        \r\n");
      out.write("        <!--End top header -->\r\n");
      out.write("\r\n");
      out.write("        <nav class=\"navbar navbar-default \">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("                <div class=\"navbar-header\">\r\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navigation\">\r\n");
      out.write("                        <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("                    <img src=\"/semi/resources/images/common/09.svg\" alt=\"\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("                <div class=\"collapse navbar-collapse yamm\" id=\"navigation\">\r\n");
      out.write("                    <div class=\"button navbar-right\" id=\"ajax_load_indicator\">\r\n");
      out.write("                   \r\n");
      out.write("                        ");
 if(mName == null){ 
      out.write("\r\n");
      out.write("                        <input type=\"button\" id=\"loginradio\" name=\"loginradio\" value=\"관리자로 전환\" onclick=\"goPage();\">\r\n");
      out.write("                        <form action=\"/semi/login\" method=\"post\">\r\n");
      out.write("                        <table width=\"250\" height=\"75\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t\t<tr><td width=\"200\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t  <input type=\"text\"  id=\"mid\" name=\"mid\" size=\"15\" required placeholder=\"아이디를 입력하세요\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"50\" rowspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"로그인\" class= \"navbar-btn nav-button wow bounceInRight login\" id=\"btnLogin\">\r\n");
      out.write("\t\t\t\t\t</td></tr>\r\n");
      out.write("\t\t\t\t<tr><td>\r\n");
      out.write("\t\t\t\t\t<!-- <input type=\"password\" name=\"userpwd\" size=\"15\"> -->\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" id=\"mpassword\" name=\"mpassword\" size=\"15\" required placeholder=\"비밀번호를 입력하세요\">\r\n");
      out.write("\t\t\t\t   </td></tr>\r\n");
      out.write("\t\t\t\t   <tr><td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/semi/views/member/memberEnroll.jsp\">회원가입</a> &nbsp;\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">아이디/암호조회</a>\r\n");
      out.write("\t\t\t\t</td></tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<table width=\"250\" height=\"75\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t<tr><td width=\"150\">\r\n");
      out.write("\t\t\t\t\t");
      out.print( mName );
      out.write(" 님. \r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"100\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/semi/logout\">로그아웃</a>\r\n");
      out.write("\t\t\t\t\t</td></tr>\r\n");
      out.write("\t\t\t\t<tr><td colspan=\"2\">\r\n");
      out.write("\t\t\t\t<a href=\"/semi/myinfo?mid=");
      out.print( mId );
      out.write("\">내 정보보기</a>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</td></tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul class=\"main-nav nav navbar-nav navbar-right\">\r\n");
      out.write("                        <li class=\"wow fadeInDown\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                           <a class=\"\" href=\"/semi/index.jsp\"> Home </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                        <li class=\"dropdown ymm-sw \" data-wow-delay=\"0.2s\">\r\n");
      out.write("                        \t<a href=\"index.html\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\" data-delay=\"200\">대여품목 <b class=\"caret\"></b></a>\r\n");
      out.write("                        \t<ul class=\"dropdown-menu navbar-nav\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">전체보기</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">- 절단공구</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">- 드릴공구</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">- 충전공구</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">- 기타공구</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">- 기타생활공구</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"dropdown ymm-sw \" data-wow-delay=\"0.3s\">\r\n");
      out.write("                        \t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\" data-delay=\"200\">게시판 <b class=\"caret\"></b></a>\r\n");
      out.write("                        \t<ul class=\"dropdown-menu navbar-nav\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">- 공지사항</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">- 문    의</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">- 후    기</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"wow fadeInDown\" data-wow-delay=\"0.4s\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-toggle\">오시는길</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                        <li class=\"wow fadeInDown\" data-wow-delay=\"0.5s\"><a href=\"#\">이용안내</a></li>\r\n");
      out.write("                      \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div><!-- /.navbar-collapse -->\r\n");
      out.write("            </div><!-- /.container-fluid -->\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!-- End of nav bar -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction dupIdCheck() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"/semi/idchk\",\r\n");
      out.write("\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\tm_id : $(\"#m_id\").val()},\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tconsole.log(\"success : \" + data);\r\n");
      out.write("\t\t\t\tif (data == \"ok\") {\r\n");
      out.write("\t\t\t\t\talert(\"사용 가능한 아이디입니다.\");\r\n");
      out.write("\t\t\t\t\t$(\"#m_name\").focus();\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert(\"이미 사용중인 아이디입니다.\\n\" + \"다시 입력하십시오.\");\r\n");
      out.write("\t\t\t\t\t$(\"#m_id\").select();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(jqXHR, textstatus, errorthrown) {\r\n");
      out.write("\t\t\t\tconsole.log(\"error : \" + jqXHR + \", \" + textstatus + \", \"\r\n");
      out.write("\t\t\t\t\t\t+ errorthrown);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 디비에 암호화 처리 -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction pwdChk(){\r\n");
      out.write("\t\tvar p1 = document.getElementById(\"pwd1\").value;\r\n");
      out.write("\t\tvar p2 = document.getElementById(\"pwd2\").value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(p1 == p2) \r\n");
      out.write("\t\t\treturn true; //submit\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\treturn false; //submit취소\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("        <table align=\"center\">\r\n");
      out.write("        <h2 align=\"center\">회 원 가 입</h2>\r\n");
      out.write("\t\t\t\t\t<form action=\"/semi/menroll.cp\" method=\"post\" onsubmit=\"return pwdChk();\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t<!-- <table align=\"center\" cellspacing=\"0\" border=\"1\"> -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>아이디</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"m_id\" class=\"form-control\" id=\"m_id\" \r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 200px; height: 25px; border-radius: 4px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button onclick=\"return dupIdCheck();\" class=\"btn btn-warning\">중복확인</button></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>비밀번호</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"password\" name=\"m_password1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" style=\"width: 200px; height: 25px; border-radius: 4px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>비밀번호 확인</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"password\" name=\"m_password2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" style=\"width: 200px; height: 25px; border-radius: 4px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>이름</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"m_name\" class=\"form-control\"\r\n");
      out.write("   \t\t\t\t\t\t\t\tstyle=\"width: 200px; height: 25px; border-radius: 4px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>닉네임</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"m_nickname\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 200px; height: 25px; border-radius: 4px;\" ></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>전화번호</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"tel\" name=\"m_phone\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 200px; height: 25px; border-radius: 4px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>주소</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" id=\"sample4_postcode\" placeholder=\"우편번호\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 200px; height: 25px; border-radius: 4px;\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\"> <input type=\"button\"\r\n");
      out.write("\t\t\t\t\tonclick=\"sample4_execDaumPostcode()\" value=\"우편번호 찾기\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 100px; height: 25px; border-radius: 4px;\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"text\" id=\"sample4_roadAddress\" placeholder=\"도로명주소\"\r\n");
      out.write("\t\t\t\t\tname=\"m_address\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 200px; height: 25px; border-radius: 4px;\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"text\" id=\"sample4_jibunAddress\" placeholder=\"지번주소\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 200px; height: 25px; border-radius: 4px;\"> <span\r\n");
      out.write("\t\t\t\t\tid=\"guide\" style=\"color: #999\"></span> \r\n");
      out.write("\t\t\t\t\t<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script> \r\n");
      out.write("\t\t\t\t\t<script charset=\"UTF-8\" type=\"text/javascript\" src=\"http://t1.daumcdn.net/postcode/api/core/180619/1529384927473/180619.js\"></script>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t//본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.\r\n");
      out.write("\t\t\t\t\t\tfunction sample4_execDaumPostcode() {\r\n");
      out.write("\t\t\t\t\t\t\tnew daum.Postcode(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\toncomplete : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t// 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t// 도로명 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t// 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar fullRoadAddr = data.roadAddress; // 도로명 주소 변수\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar extraRoadAddr = ''; // 도로명 조합형 주소 변수\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t// 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t// 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif (data.bname !== ''\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t&& /[동|로|가]$/g\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.test(data.bname)) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\textraRoadAddr += data.bname;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t// 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif (data.buildingName !== ''\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t&& data.apartment === 'Y') {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\textraRoadAddr += (extraRoadAddr !== '' ? ', '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ data.buildingName\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t: data.buildingName);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t// 도로명, 지번 조합형 주소가 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif (extraRoadAddr !== '') {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\textraRoadAddr = ' ('\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ extraRoadAddr + ')';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t// 도로명, 지번 주소의 유무에 따라 해당 조합형 주소를 추가한다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif (fullRoadAddr !== '') {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tfullRoadAddr += extraRoadAddr;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t// 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.getElementById('sample4_postcode').value = data.zonecode; //5자리 새우편번호 사용\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.getElementById('sample4_roadAddress').value = fullRoadAddr;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.getElementById('sample4_jibunAddress').value = data.jibunAddress;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t// 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif (data.autoRoadAddress) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t//예상되는 도로명 주소에 조합형 주소를 추가한다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar expRoadAddr = data.autoRoadAddress\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ extraRoadAddr;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t.getElementById('guide').innerHTML = '(예상 도로명 주소 : '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ expRoadAddr + ')';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t} else if (data.autoJibunAddress) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar expJibunAddr = data.autoJibunAddress;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t.getElementById('guide').innerHTML = '(예상 지번 주소 : '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ expJibunAddr + ')';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t.getElementById('guide').innerHTML = '';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}).open();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t</script></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>이메일</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"email\" name=\"m_email\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 200px; height: 25px; border-radius: 4px;\">\r\n");
      out.write("\t\t\t\t\t<button id=\"checkemail\" onclick=\"window.open('address','window_name','width=400,height=350,location=no,status=no,scrollbars=yes');\">이메일인증</button></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>생년월일</td>\r\n");
      out.write("\t\t\t\t\t<td><script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\tvar today = new Date();\r\n");
      out.write("\t\t\t\t\t\tvar toyear = parseInt(today.getFullYear());\r\n");
      out.write("\t\t\t\t\t\tvar start = toyear;\r\n");
      out.write("\t\t\t\t\t\tvar end = toyear - 70;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t\t\t\t.write(\"<font size=2><select name=birth1>\");\r\n");
      out.write("\t\t\t\t\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t\t\t\t.write(\"<option value='' selected>\");\r\n");
      out.write("\t\t\t\t\t\t\t\tfor (i = start; i >= end; i--)\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write(\"<option>\" + i);\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write(\"</select>년  \");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write(\"<select name=birth2>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t.write(\"<option value='' selected>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfor (i = 1; i <= 12; i++)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write(\"<option>\" + i);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write(\"</select>월  \");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write(\"<select name=birth3>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t.write(\"<option value='' selected>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfor (i = 1; i <= 31; i++)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write(\"<option>\" + i);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write(\"</select>일   </font>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t</script> \r\n");
      out.write("\t\t\t\t\t</tr><br>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t \t\t<td>성별</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"radio\" name=\"m_gender\" value=\"M\" style=\"MARGIN: 0px 3px 1px 0px; WIDTH: 13px; HEIGHT: 13px \r\n");
      out.write("\t\t\t\t\t\t\t\tborder-radius: 4px;\">남&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"m_gender\" value=\"F\" style=\"MARGIN: 0px 3px 1px 0px; WIDTH: 13px; HEIGHT: 13px \r\n");
      out.write("\t\t\t\t\t\t\t\tborder-radius: 4px;\">여</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\"value=\"가입하기\" style=\"width: 150px; height: 30px; border-radius: 4px;\">&nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"reset\" value=\"취소\" style=\"width: 150px; height: 30px; border-radius: 4px;\" onclick=\"location.href='/semi/index.jsp'\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!-- boy-sale area -->\r\n");
      out.write("        <div class=\"boy-sale-area\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-6 col-sm-10 col-sm-offset-1 col-md-offset-0 col-xs-12\">\r\n");
      out.write("                        <div class=\"asks-first\">\r\n");
      out.write("                            <div class=\"asks-first-circle\">\r\n");
      out.write("                                <span class=\"fa fa-search\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"asks-first-info\">\r\n");
      out.write("                                <h2>ARE YOU LOOKING FOR A Property?</h2>\r\n");
      out.write("                                <p> varius od lio eget conseq uat blandit, lorem auglue comm lodo nisl no us nibh mas lsa</p>                                        \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"asks-first-arrow\">\r\n");
      out.write("                                <a href=\"properties.html\"><span class=\"fa fa-angle-right\"></span></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6 col-sm-10 col-sm-offset-1 col-xs-12 col-md-offset-0\">\r\n");
      out.write("                        <div  class=\"asks-first\">\r\n");
      out.write("                            <div class=\"asks-first-circle\">\r\n");
      out.write("                                <span class=\"fa fa-usd\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"asks-first-info\">\r\n");
      out.write("                                <h2>DO YOU WANT TO SELL A Property?</h2>\r\n");
      out.write("                                <p> varius od lio eget conseq uat blandit, lorem auglue comm lodo nisl no us nibh mas lsa</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"asks-first-arrow\">\r\n");
      out.write("                                <a href=\"properties.html\"><span class=\"fa fa-angle-right\"></span></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xs-12\">\r\n");
      out.write("                        <p  class=\"asks-call\">QUESTIONS? CALL US  : <span class=\"strong\"> + 3-123- 424-5700</span></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Footer area-->\r\n");
      out.write("        <div class=\"footer-area\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\" footer\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-md-3 col-sm-6 wow fadeInRight animated\">\r\n");
      out.write("                            <div class=\"single-footer\">\r\n");
      out.write("                                <h4>About us </h4>\r\n");
      out.write("                                <div class=\"footer-title-line\"></div>\r\n");
      out.write("\r\n");
      out.write("                                <img src=\"/semi/assets/img/footer-logo.png\" alt=\"\" class=\"wow pulse\" data-wow-delay=\"1s\">\r\n");
      out.write("                                <p>Lorem ipsum dolor cum necessitatibus su quisquam molestias. Vel unde, blanditiis.</p>\r\n");
      out.write("                                <ul class=\"footer-adress\">\r\n");
      out.write("                                    <li><i class=\"pe-7s-map-marker strong\"> </i> 9089 your adress her</li>\r\n");
      out.write("                                    <li><i class=\"pe-7s-mail strong\"> </i> email@yourcompany.com</li>\r\n");
      out.write("                                    <li><i class=\"pe-7s-call strong\"> </i> +1 908 967 5906</li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3 col-sm-6 wow fadeInRight animated\">\r\n");
      out.write("                            <div class=\"single-footer\">\r\n");
      out.write("                                <h4>Quick links </h4>\r\n");
      out.write("                                <div class=\"footer-title-line\"></div>\r\n");
      out.write("                                <ul class=\"footer-menu\">\r\n");
      out.write("                                    <li><a href=\"properties.html\">Properties</a>  </li> \r\n");
      out.write("                                    <li><a href=\"#\">Services</a>  </li> \r\n");
      out.write("                                    <li><a href=\"submit-property.html\">Submit property </a></li> \r\n");
      out.write("                                    <li><a href=\"contact.html\">Contact us</a></li> \r\n");
      out.write("                                    <li><a href=\"faq.html\">fqa</a>  </li> \r\n");
      out.write("                                    <li><a href=\"faq.html\">Terms </a>  </li> \r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3 col-sm-6 wow fadeInRight animated\">\r\n");
      out.write("                            <div class=\"single-footer\">\r\n");
      out.write("                                <h4>Last News</h4>\r\n");
      out.write("                                <div class=\"footer-title-line\"></div>\r\n");
      out.write("                                <ul class=\"footer-blog\">\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"col-md-3 col-sm-4 col-xs-4 blg-thumb p0\">\r\n");
      out.write("                                            <a href=\"single.html\">\r\n");
      out.write("                                                <img src=\"assets/img/demo/small-proerty-2.jpg\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <span class=\"blg-date\">12-12-2016</span>\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-8  col-sm-8 col-xs-8  blg-entry\">\r\n");
      out.write("                                            <h6> <a href=\"single.html\">Add news functions </a></h6> \r\n");
      out.write("                                            <p style=\"line-height: 17px; padding: 8px 2px;\">Lorem ipsum dolor sit amet, nulla ...</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li> \r\n");
      out.write("\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"col-md-3 col-sm-4 col-xs-4 blg-thumb p0\">\r\n");
      out.write("                                            <a href=\"single.html\">\r\n");
      out.write("                                                <img src=\"/semi/assets/img/demo/small-proerty-2.jpg\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <span class=\"blg-date\">12-12-2016</span>\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-8  col-sm-8 col-xs-8  blg-entry\">\r\n");
      out.write("                                            <h6> <a href=\"/semi/single.html\">Add news functions </a></h6> \r\n");
      out.write("                                            <p style=\"line-height: 17px; padding: 8px 2px;\">Lorem ipsum dolor sit amet, nulla ...</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li> \r\n");
      out.write("\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"col-md-3 col-sm-4 col-xs-4 blg-thumb p0\">\r\n");
      out.write("                                            <a href=\"single.html\">\r\n");
      out.write("                                                <img src=\"/semi/assets/img/demo/small-proerty-2.jpg\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <span class=\"blg-date\">12-12-2016</span>\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-8  col-sm-8 col-xs-8  blg-entry\">\r\n");
      out.write("                                            <h6> <a href=\"single.html\">Add news functions </a></h6> \r\n");
      out.write("                                            <p style=\"line-height: 17px; padding: 8px 2px;\">Lorem ipsum dolor sit amet, nulla ...</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3 col-sm-6 wow fadeInRight animated\">\r\n");
      out.write("                            <div class=\"single-footer news-letter\">\r\n");
      out.write("                                <h4>Stay in touch</h4>\r\n");
      out.write("                                <div class=\"footer-title-line\"></div>\r\n");
      out.write("                                <p>Lorem ipsum dolor sit amet, nulla  suscipit similique quisquam molestias. Vel unde, blanditiis.</p>\r\n");
      out.write("\r\n");
      out.write("                                <form>\r\n");
      out.write("                                    <div class=\"input-group\">\r\n");
      out.write("                                        <input class=\"form-control\" type=\"text\" placeholder=\"E-mail ... \">\r\n");
      out.write("                                        <span class=\"input-group-btn\">\r\n");
      out.write("                                            <button class=\"btn btn-primary subscribe\" type=\"button\"><i class=\"pe-7s-paper-plane pe-2x\"></i></button>\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- /input-group -->\r\n");
      out.write("                                </form> \r\n");
      out.write("\r\n");
      out.write("                                <div class=\"social pull-right\"> \r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a class=\"wow fadeInUp animated\" href=\"https://twitter.com/kimarotec\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("                                        <li><a class=\"wow fadeInUp animated\" href=\"https://www.facebook.com/kimarotec\" data-wow-delay=\"0.2s\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("                                        <li><a class=\"wow fadeInUp animated\" href=\"https://plus.google.com/kimarotec\" data-wow-delay=\"0.3s\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("                                        <li><a class=\"wow fadeInUp animated\" href=\"https://instagram.com/kimarotec\" data-wow-delay=\"0.4s\"><i class=\"fa fa-instagram\"></i></a></li>\r\n");
      out.write("                                        <li><a class=\"wow fadeInUp animated\" href=\"https://instagram.com/kimarotec\" data-wow-delay=\"0.6s\"><i class=\"fa fa-dribbble\"></i></a></li>\r\n");
      out.write("                                    </ul> \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"footer-copy text-center\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"pull-left\">\r\n");
      out.write("                            <span> (C) <a href=\"http://www.KimaroTec.com\">KimaroTheme</a> , All rights reserved 2016  </span> \r\n");
      out.write("                        </div> \r\n");
      out.write("                        <div class=\"bottom-menu pull-right\"> \r\n");
      out.write("                            <ul> \r\n");
      out.write("                                <li><a class=\"wow fadeInUp animated\" href=\"#\" data-wow-delay=\"0.2s\">Home</a></li>\r\n");
      out.write("                                <li><a class=\"wow fadeInUp animated\" href=\"#\" data-wow-delay=\"0.3s\">Property</a></li>\r\n");
      out.write("                                <li><a class=\"wow fadeInUp animated\" href=\"#\" data-wow-delay=\"0.4s\">Faq</a></li>\r\n");
      out.write("                                <li><a class=\"wow fadeInUp animated\" href=\"#\" data-wow-delay=\"0.6s\">Contact</a></li>\r\n");
      out.write("                            </ul> \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<script src=\"/semi/resources/js/modernizr-2.6.2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"/semi/resources/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("        <script src=\"/semi/resources/js/bootstrap-select.min.js\"></script>\r\n");
      out.write("        <script src=\"/semi/resources/js/bootstrap-hover-dropdown.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"/semi/resources/js/easypiechart.min.js\"></script>\r\n");
      out.write("        <script src=\"/semi/resources/js/jquery.easypiechart.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"/semi/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("        <script src=\"/semi/resources/js/wow.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <script src=\"/semi/resources/js/price-range.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"/semi/resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
