/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2018-08-20 07:29:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import semi.member.model.vo.Member;
import java.util.*;

public final class myInfoView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/views/member/../../end.jsp", Long.valueOf(1534417878888L));
    _jspx_dependants.put("/views/member/../../head.jsp", Long.valueOf(1534489056336L));
    _jspx_dependants.put("/views/member/../../aside2.jsp", Long.valueOf(1534162320037L));
    _jspx_dependants.put("/views/member/../../footer.jsp", Long.valueOf(1534236327074L));
    _jspx_dependants.put("/views/member/../../header.jsp", Long.valueOf(1534589436830L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("semi.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  \r\n");

	Member member = (Member)request.getAttribute("member");
	String mid = (String)session.getAttribute("m_id");

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	String mName = (String)session.getAttribute("m_Name");
	String mId = (String)session.getAttribute("m_Id");
	String mPassword = (String)session.getAttribute("m_password");


      out.write("\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"description\" content=\"GARO is a real-estate template\">\r\n");
      out.write("<meta name=\"author\" content=\"Kimarotec\">\r\n");
      out.write("<meta name=\"keyword\" content=\"html5, css, bootstrap, property, real-estate theme , bootstrap template\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("<link rel=\"icon\" href=\"favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/normalize.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/fontello.css\">\r\n");
      out.write("<link href=\"/semi/resources/fonts/icon-7-stroke/css/pe-icon-7-stroke.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/semi/resources/fonts/icon-7-stroke/css/helper.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/semi/resources/css/animate.css\" rel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/bootstrap-select.min.css\"> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/icheck.min_all.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/price-range.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/owl.carousel.css\">  \r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/owl.theme.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/owl.transitions.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/responsive.css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/semi/resources/js/jquery/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<title>09빌려줘</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 바디까지!! -->");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#btnLogin\").click(function(){\r\n");
      out.write("\t\t\t\t\tvar mid = $(\"#mid\").val();\r\n");
      out.write("\t\t\t\t\tvar mpassword = $(\"#mpassword\").val();\r\n");
      out.write("\t\t\t\t\tvar exp = /[a-z0-9]$/;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(mid == \"\"){\r\n");
      out.write("\t\t\t\t\t\talert(\"아이디를 입력해주세요\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#mid\").focus();\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(!exp.test(mid)){\r\n");
      out.write("\t\t\t\t\t\talert(\"영문자와 숫자만 입력가능합니다.\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#mid\").focus();\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t    if (mpassword == \"\") {\r\n");
      out.write("\t\t                alert(\"비밀번호를 입력해주세요\");\r\n");
      out.write("\t\t                $(\"#mpassword\").focus();\r\n");
      out.write("\t\t                return;\r\n");
      out.write("\t\t            }\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction goPage(){\r\n");
      out.write("\t\t\t\tlocation.href = \"/semi/adminIndex.jsp\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("        <style type=\"text/css\">\r\n");
      out.write("        input::placeholder {\r\n");
      out.write("  \t\t\tcolor: #aaaaaa;\r\n");
      out.write("\t\t\tfont-size : 10px;\r\n");
      out.write("\t\t}\r\n");
      out.write("        </style>\r\n");
      out.write("        <!-- Body content -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"header-connect\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-5 col-sm-8  col-xs-12\">\r\n");
      out.write("                        <div class=\"header-half header-call\">\r\n");
      out.write("                            <p>\r\n");
      out.write("                                <span><i class=\"pe-7s-call\"></i> 010-1234-5678</span>\r\n");
      out.write("                                <span><i class=\"pe-7s-mail\"></i> hongildong@iei\t.org</span>\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-2 col-md-offset-5  col-sm-3 col-sm-offset-1  col-xs-12\">\r\n");
      out.write("                        <div class=\"header-half header-social\">\r\n");
      out.write("                            <ul class=\"list-inline\">\r\n");
      out.write("                             \r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>        \r\n");
      out.write("        <!--End top header -->\r\n");
      out.write("\r\n");
      out.write("        <nav class=\"navbar navbar-default \">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("                <div class=\"navbar-header\">\r\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navigation\">\r\n");
      out.write("                        <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("                    <img src=\"/semi/resources/images/common/09.svg\" alt=\"\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("                <div class=\"collapse navbar-collapse yamm\" id=\"navigation\">\r\n");
      out.write("                    <div class=\"button navbar-right\" id=\"ajax_load_indicator\">\r\n");
      out.write("                   \r\n");
      out.write("                        ");
 if(mName == null){ 
      out.write("\r\n");
      out.write("                        <input type=\"button\" id=\"loginradio\" name=\"loginradio\" value=\"관리자로 전환\" onclick=\"goPage();\">\r\n");
      out.write("                        <form action=\"/semi/login\" method=\"post\">\r\n");
      out.write("                        <table width=\"250\" height=\"75\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t\t<tr><td width=\"200\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t  <input type=\"text\"  id=\"mid\" name=\"mid\" size=\"15\" required placeholder=\"아이디를 입력하세요\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"50\" rowspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"로그인\" class= \"navbar-btn nav-button wow bounceInRight login\" id=\"btnLogin\">\r\n");
      out.write("\t\t\t\t\t</td></tr>\r\n");
      out.write("\t\t\t\t<tr><td>\r\n");
      out.write("\t\t\t\t\t<!-- <input type=\"password\" name=\"userpwd\" size=\"15\"> -->\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" id=\"mpassword\" name=\"mpassword\" size=\"15\" required placeholder=\"비밀번호를 입력하세요\">\r\n");
      out.write("\t\t\t\t   </td></tr>\r\n");
      out.write("\t\t\t\t   <tr><td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/semi/views/member/memberEnroll.jsp\">회원가입</a> &nbsp;\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">아이디/암호조회</a>\r\n");
      out.write("\t\t\t\t</td></tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<table width=\"250\" height=\"75\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t<tr><td width=\"150\">\r\n");
      out.write("\t\t\t\t\t");
      out.print( mName );
      out.write(" 님. \r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"100\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/semi/logout\">로그아웃</a>\r\n");
      out.write("\t\t\t\t\t</td></tr>\r\n");
      out.write("\t\t\t\t<tr><td colspan=\"2\">\r\n");
      out.write("\t\t\t\t<a href=\"/semi/myinfo?mid=");
      out.print( mId );
      out.write("\">내 정보보기</a>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</td></tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul class=\"main-nav nav navbar-nav navbar-right\">\r\n");
      out.write("                        <li class=\"wow fadeInDown\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                           <a class=\"\" href=\"/semi/index.jsp\"> Home </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                        <li class=\"dropdown ymm-sw \" data-wow-delay=\"0.2s\">\r\n");
      out.write("                        \t<a href=\"index.html\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\" data-delay=\"200\">대여품목 <b class=\"caret\"></b></a>\r\n");
      out.write("                        \t<ul class=\"dropdown-menu navbar-nav\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"/semi/views/payment/paymentProgressView.jsp\">전체보기</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">- 절단공구</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">- 드릴공구</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">- 충전공구</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">- 기타공구</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">- 기타생활공구</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"dropdown ymm-sw \" data-wow-delay=\"0.3s\">\r\n");
      out.write("                        \t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\" data-delay=\"200\">게시판 <b class=\"caret\"></b></a>\r\n");
      out.write("                        \t<ul class=\"dropdown-menu navbar-nav\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">- 공지사항</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">- 문    의</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">- 후    기</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"wow fadeInDown\" data-wow-delay=\"0.4s\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-toggle\">오시는길</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                        <li class=\"wow fadeInDown\" data-wow-delay=\"0.5s\"><a href=\"#\">이용안내</a></li>\r\n");
      out.write("                      \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div><!-- /.navbar-collapse -->\r\n");
      out.write("            </div><!-- /.container-fluid -->\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!-- End of nav bar -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#allbutton { width : 68px; height : 30px; font : 7px Sans-Serif; position : absolute; right : 45px; bottom : 160px;}\r\n");
      out.write("\t#recentTable th{align : center;}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t//암호 입력 상자에서 포커스가 사라질 때 암호확인 처리함\r\n");
      out.write("\t\t$(\"#pwd2\").blur(function(){\r\n");
      out.write("\t\t\tconsole.log(\"포커스가 사라짐...\");\r\n");
      out.write("\t\t\tvar pwd1 = $(\"#pwd1\").val();\r\n");
      out.write("\t\t\tvar pwd2 = $(\"#pwd2\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(pwd1 != pwd2){\r\n");
      out.write("\t\t\t\talert(\"암호와 암호확인이 일치하지 않습니다.\");\r\n");
      out.write("\t\t\t\t$(\"#pwd1\").select();\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" var stmnLEFT = 10; // 오른쪽 여백 \r\n");
      out.write(" var stmnGAP1 = 0; // 위쪽 여백 \r\n");
      out.write(" var stmnGAP2 = 150; // 스크롤시 브라우저 위쪽과 떨어지는 거리 \r\n");
      out.write(" var stmnBASE = 150; // 스크롤 시작위치 \r\n");
      out.write(" var stmnActivateSpeed = 25; //스크롤을 인식하는 딜레이 (숫자가 클수록 느리게 인식)\r\n");
      out.write(" var stmnScrollSpeed = 20; //스크롤 속도 (클수록 느림)\r\n");
      out.write(" var stmnTimer; \r\n");
      out.write(" \r\n");
      out.write(" function RefreshStaticMenu() { \r\n");
      out.write("  var stmnStartPoint, stmnEndPoint; \r\n");
      out.write("  stmnStartPoint = parseInt(document.getElementById('STATICMENU').style.top, 10); \r\n");
      out.write("  stmnEndPoint = Math.max(document.documentElement.scrollTop, document.body.scrollTop) + stmnGAP2; \r\n");
      out.write("  if (stmnEndPoint < stmnGAP1) stmnEndPoint = stmnGAP1; \r\n");
      out.write("  if (stmnStartPoint != stmnEndPoint) { \r\n");
      out.write("   stmnScrollAmount = Math.ceil( Math.abs( stmnEndPoint - stmnStartPoint ) / 15 ); \r\n");
      out.write("   document.getElementById('STATICMENU').style.top = parseInt(document.getElementById('STATICMENU').style.top, 10) \r\n");
      out.write("   \t\t\t\t\t\t\t+ ( ( stmnEndPoint<stmnStartPoint ) ? -stmnScrollAmount : stmnScrollAmount ) + 'px'; \r\n");
      out.write("   stmnRefreshTimer = stmnScrollSpeed; \r\n");
      out.write("   }\r\n");
      out.write("  stmnTimer = setTimeout(\"RefreshStaticMenu();\", stmnActivateSpeed); \r\n");
      out.write("  } \r\n");
      out.write(" function InitializeStaticMenu() {\r\n");
      out.write("  document.getElementById('STATICMENU').style.right = stmnLEFT + 'px';  //처음에 오른쪽에 위치. left로 바꿔도.\r\n");
      out.write("  document.getElementById('STATICMENU').style.top = document.body.scrollTop + stmnBASE + 'px'; \r\n");
      out.write("  RefreshStaticMenu();\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#STATICMENU { margin: 15pt; padding: 0pt;  position: absolute; right: 0px; top: 0px; width: 120px; height : 160px; }  \r\n");
      out.write("#bannerRightId{ background: black; color: white;}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"본래 설정\" onload=\"InitializeStaticMenu();\">\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<div id=\"STATICMENU\">\r\n");
      out.write("<a id=\"bannerRightId\">오늘 본 상품</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<div class=\"page-head\"> \r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"page-head-content\">\r\n");
      out.write("                        <h1 class=\"page-title\">09 : <span class=\"orange strong\">My Page</span></h1>               \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End page header --> \r\n");
      out.write("\r\n");
      out.write("<h1 align=\"center\"><b>");
      out.print( member.getmName() );
      out.write("</b> 님의 정보</h1><br>\r\n");
      out.write("\r\n");
      out.write("<form action=\"/semi/mupdate\" method=\"post\">\r\n");
      out.write("<table width=\"600\" align=\"center\" cellspacing=\"5\" \r\n");
      out.write("bgcolor=\"#3399ff\">\r\n");
      out.write("<tr><td><label>아이디</label></td>\r\n");
      out.write("<td>\r\n");
      out.write("\t<input type=\"text\" name=\"mid\" \r\n");
      out.write("\tvalue=\"");
      out.print( member.getmId() );
      out.write("\" readonly>\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td><label>이 름</label></td>\r\n");
      out.write("<td>\r\n");
      out.write("\t<input type=\"text\" name=\"mname\" \r\n");
      out.write("\tvalue=\"");
      out.print( member.getmName() );
      out.write("\" readonly>\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td><label>암 호</label></td>\r\n");
      out.write("<td>\r\n");
      out.write("\t<input type=\"password\" name=\"mpassword\" id=\"pwd1\"\r\n");
      out.write("\tvalue=\"");
      out.print( member.getmPassword() );
      out.write("\">\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td><label>암호확인</label></td>\r\n");
      out.write("<td>\r\n");
      out.write("\t<input type=\"password\" id=\"pwd2\">\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td><label>닉네임</label></td>\r\n");
      out.write("<td>\r\n");
      out.write("\t<input type=\"text\" name=\"mnickname\"\r\n");
      out.write("\tvalue=\"");
      out.print( member.getmNickname() );
      out.write("\">\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td><label>포인트</label></td>\r\n");
      out.write("<td>\r\n");
      out.write("\t<input type=\"text\" name=\"mpoint\"\r\n");
      out.write("\tvalue=\"");
      out.print( member.getmPoint() );
      out.write("\" readonly>\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td><label>성 별</label></td>\r\n");
      out.write("<td>\r\n");
      out.write("\t");
 if(member.getmGender().equals("M")){ 
      out.write("\r\n");
      out.write("\t<input type=\"radio\" name=\"mgender\" value=\"M\" checked> 남 &nbsp;\r\n");
      out.write("\t<input type=\"radio\" name=\"mgender\" value=\"F\"> 여\r\n");
      out.write("\t");
 }else{ 
      out.write("\r\n");
      out.write("\t<input type=\"radio\" name=\"mgender\" value=\"M\"> 남 &nbsp;\r\n");
      out.write("\t<input type=\"radio\" name=\"mgender\" value=\"F\" checked> 여\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td><label>주 소</label></td>\r\n");
      out.write("<td>\r\n");
      out.write("\t<input type=\"text\" name=\"maddress\" \r\n");
      out.write("\tvalue=\"");
      out.print( member.getmAddress() );
      out.write("\">\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td><label>전화번호</label></td>\r\n");
      out.write("<td>\r\n");
      out.write("\t<input type=\"tel\" name=\"mphone\" \r\n");
      out.write("\tvalue=\"");
      out.print( member.getmPhone() );
      out.write("\">\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td><label>이메일</label></td>\r\n");
      out.write("<td>\r\n");
      out.write("\t<input type=\"email\" name=\"memail\" \r\n");
      out.write("\tvalue=\"");
      out.print( member.getmEmail() );
      out.write("\">\r\n");
      out.write("</td></tr>\t\r\n");
      out.write("<tr>\r\n");
      out.write("<tr><td><label>생년월일</label></td>\r\n");
      out.write("<td>\r\n");
      out.write("\t<input type=\"text\" name=\"msno\" \r\n");
      out.write("\tvalue=\"");
      out.print( member.getmSno() );
      out.write("\" readonly>\r\n");
      out.write("</td></tr>\t\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t\t<input type=\"submit\" value=\"수정하기\" class=\"btn btn-default\">\r\n");
      out.write("\t\t&nbsp; &nbsp;\r\n");
      out.write("\t\t<a href=\"/semi/mdelete?mid=");
      out.print( member.getmId() );
      out.write("\">탈퇴하기</a>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("</form>\r\n");
      out.write("<div class=\"clear\">\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\t<button class=\"btn btn-default btn-lg\"\r\n");
      out.write("\t\tstyle=\"background: white; margin-left: 670px;\">\r\n");
      out.write("\t\t<a href=\"/semi/myinfo?mid=");
      out.print( member.getmId() );
      out.write("\"\r\n");
      out.write("\t\t\tstyle=\"color: black;\">Home</a>\r\n");
      out.write("\t</button>\r\n");
      out.write("\t<button class=\"btn btn-default btn-lg\" style=\"background: white;\">\r\n");
      out.write("\t\t<a href=\"/semi/mypoint?mid=");
      out.print( member.getmId() );
      out.write("\"\r\n");
      out.write("\t\t\tstyle=\"color: black;\">포인트 내역</a>\r\n");
      out.write("\t</button>\r\n");
      out.write("\t<button class=\"btn btn-default btn-lg\" style=\"background: white;\">\r\n");
      out.write("\t\t<a href=\"/semi/myrent?mid=");
      out.print( member.getmId() );
      out.write("\"\r\n");
      out.write("\t\t\tstyle=\"color: black;\">최근 대여목록</a>\r\n");
      out.write("\t</button>\r\n");
      out.write("\t<button class=\"btn btn-default btn-lg\" style=\"background: white;\">\r\n");
      out.write("\t\t<a style=\"color: black;\">나의 게시글</a>\r\n");
      out.write("\t</button>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"col-sm-5 col-sm-offset-1\">\r\n");
      out.write("\t\t<!-- 최근 대여목록 -->\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<table align=\"center\" border=\"1\" cellspacing=\"0\" width=\"700\"\r\n");
      out.write("\t\t\t\tstyle=\"position: relative;\" id=\"recentTable\">\r\n");
      out.write("\t\t\t\t<a>최근 대여 목록</a>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<button id=\"allbutton\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/semi/mypoint?mid=");
      out.print( member.getmId() );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"color: #777;\">전체보기</a>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>대여번호</th>\r\n");
      out.write("\t\t\t\t\t<th>상품번호</th>\r\n");
      out.write("\t\t\t\t\t<th>대여 일자</th>\r\n");
      out.write("\t\t\t\t\t<th>상품명 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;\r\n");
      out.write("\t\t\t\t\t\t&nbsp;</th>\r\n");
      out.write("\t\t\t\t\t<th>금액 &nbsp; &nbsp; &nbsp;</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>1</td>\r\n");
      out.write("\t\t\t\t\t<td>2</td>\r\n");
      out.write("\t\t\t\t\t<td>3</td>\r\n");
      out.write("\t\t\t\t\t<td>4</td>\r\n");
      out.write("\t\t\t\t\t<td>5</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>1</td>\r\n");
      out.write("\t\t\t\t\t<td>2</td>\r\n");
      out.write("\t\t\t\t\t<td>3</td>\r\n");
      out.write("\t\t\t\t\t<td>4</td>\r\n");
      out.write("\t\t\t\t\t<td>5</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>1</td>\r\n");
      out.write("\t\t\t\t\t<td>2</td>\r\n");
      out.write("\t\t\t\t\t<td>3</td>\r\n");
      out.write("\t\t\t\t\t<td>4</td>\r\n");
      out.write("\t\t\t\t\t<td>5</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"col-sm-5\">\r\n");
      out.write("\t\t<!-- 나의 게시글 -->\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label>Public email :</label> <input name=\"p-email\" type=\"email\"\r\n");
      out.write("\t\t\t\tclass=\"form-control\" placeholder=\"p-email@rmail.com\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label>Phone :</label> <input name=\"Phone\" type=\"text\"\r\n");
      out.write("\t\t\t\tclass=\"form-control\" placeholder=\"+1 9090909090\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label>FAX :</label> <input name=\"FAX\" type=\"text\"\r\n");
      out.write("\t\t\t\tclass=\"form-control\" placeholder=\"+1 9090909090\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!-- boy-sale area -->\r\n");
      out.write("        <div class=\"boy-sale-area\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-6 col-sm-10 col-sm-offset-1 col-md-offset-0 col-xs-12\">\r\n");
      out.write("                        <div class=\"asks-first\">\r\n");
      out.write("                            <div class=\"asks-first-circle\">\r\n");
      out.write("                                <span class=\"fa fa-search\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"asks-first-info\">\r\n");
      out.write("                                <h2>ARE YOU LOOKING FOR A Property?</h2>\r\n");
      out.write("                                <p> varius od lio eget conseq uat blandit, lorem auglue comm lodo nisl no us nibh mas lsa</p>                                        \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"asks-first-arrow\">\r\n");
      out.write("                                <a href=\"properties.html\"><span class=\"fa fa-angle-right\"></span></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6 col-sm-10 col-sm-offset-1 col-xs-12 col-md-offset-0\">\r\n");
      out.write("                        <div  class=\"asks-first\">\r\n");
      out.write("                            <div class=\"asks-first-circle\">\r\n");
      out.write("                                <span class=\"fa fa-usd\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"asks-first-info\">\r\n");
      out.write("                                <h2>DO YOU WANT TO SELL A Property?</h2>\r\n");
      out.write("                                <p> varius od lio eget conseq uat blandit, lorem auglue comm lodo nisl no us nibh mas lsa</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"asks-first-arrow\">\r\n");
      out.write("                                <a href=\"properties.html\"><span class=\"fa fa-angle-right\"></span></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xs-12\">\r\n");
      out.write("                        <p  class=\"asks-call\">QUESTIONS? CALL US  : <span class=\"strong\"> + 3-123- 424-5700</span></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Footer area-->\r\n");
      out.write("        <div class=\"footer-area\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\" footer\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-md-3 col-sm-6 wow fadeInRight animated\">\r\n");
      out.write("                            <div class=\"single-footer\">\r\n");
      out.write("                                <h4>About us </h4>\r\n");
      out.write("                                <div class=\"footer-title-line\"></div>\r\n");
      out.write("\r\n");
      out.write("                                <img src=\"/semi/assets/img/footer-logo.png\" alt=\"\" class=\"wow pulse\" data-wow-delay=\"1s\">\r\n");
      out.write("                                <p>Lorem ipsum dolor cum necessitatibus su quisquam molestias. Vel unde, blanditiis.</p>\r\n");
      out.write("                                <ul class=\"footer-adress\">\r\n");
      out.write("                                    <li><i class=\"pe-7s-map-marker strong\"> </i> 9089 your adress her</li>\r\n");
      out.write("                                    <li><i class=\"pe-7s-mail strong\"> </i> email@yourcompany.com</li>\r\n");
      out.write("                                    <li><i class=\"pe-7s-call strong\"> </i> +1 908 967 5906</li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3 col-sm-6 wow fadeInRight animated\">\r\n");
      out.write("                            <div class=\"single-footer\">\r\n");
      out.write("                                <h4>Quick links </h4>\r\n");
      out.write("                                <div class=\"footer-title-line\"></div>\r\n");
      out.write("                                <ul class=\"footer-menu\">\r\n");
      out.write("                                    <li><a href=\"properties.html\">Properties</a>  </li> \r\n");
      out.write("                                    <li><a href=\"#\">Services</a>  </li> \r\n");
      out.write("                                    <li><a href=\"submit-property.html\">Submit property </a></li> \r\n");
      out.write("                                    <li><a href=\"contact.html\">Contact us</a></li> \r\n");
      out.write("                                    <li><a href=\"faq.html\">fqa</a>  </li> \r\n");
      out.write("                                    <li><a href=\"faq.html\">Terms </a>  </li> \r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3 col-sm-6 wow fadeInRight animated\">\r\n");
      out.write("                            <div class=\"single-footer\">\r\n");
      out.write("                                <h4>Last News</h4>\r\n");
      out.write("                                <div class=\"footer-title-line\"></div>\r\n");
      out.write("                                <ul class=\"footer-blog\">\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"col-md-3 col-sm-4 col-xs-4 blg-thumb p0\">\r\n");
      out.write("                                            <a href=\"single.html\">\r\n");
      out.write("                                                <img src=\"assets/img/demo/small-proerty-2.jpg\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <span class=\"blg-date\">12-12-2016</span>\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-8  col-sm-8 col-xs-8  blg-entry\">\r\n");
      out.write("                                            <h6> <a href=\"single.html\">Add news functions </a></h6> \r\n");
      out.write("                                            <p style=\"line-height: 17px; padding: 8px 2px;\">Lorem ipsum dolor sit amet, nulla ...</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li> \r\n");
      out.write("\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"col-md-3 col-sm-4 col-xs-4 blg-thumb p0\">\r\n");
      out.write("                                            <a href=\"single.html\">\r\n");
      out.write("                                                <img src=\"/semi/assets/img/demo/small-proerty-2.jpg\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <span class=\"blg-date\">12-12-2016</span>\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-8  col-sm-8 col-xs-8  blg-entry\">\r\n");
      out.write("                                            <h6> <a href=\"/semi/single.html\">Add news functions </a></h6> \r\n");
      out.write("                                            <p style=\"line-height: 17px; padding: 8px 2px;\">Lorem ipsum dolor sit amet, nulla ...</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li> \r\n");
      out.write("\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"col-md-3 col-sm-4 col-xs-4 blg-thumb p0\">\r\n");
      out.write("                                            <a href=\"single.html\">\r\n");
      out.write("                                                <img src=\"/semi/assets/img/demo/small-proerty-2.jpg\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <span class=\"blg-date\">12-12-2016</span>\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-8  col-sm-8 col-xs-8  blg-entry\">\r\n");
      out.write("                                            <h6> <a href=\"single.html\">Add news functions </a></h6> \r\n");
      out.write("                                            <p style=\"line-height: 17px; padding: 8px 2px;\">Lorem ipsum dolor sit amet, nulla ...</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3 col-sm-6 wow fadeInRight animated\">\r\n");
      out.write("                            <div class=\"single-footer news-letter\">\r\n");
      out.write("                                <h4>Stay in touch</h4>\r\n");
      out.write("                                <div class=\"footer-title-line\"></div>\r\n");
      out.write("                                <p>Lorem ipsum dolor sit amet, nulla  suscipit similique quisquam molestias. Vel unde, blanditiis.</p>\r\n");
      out.write("\r\n");
      out.write("                                <form>\r\n");
      out.write("                                    <div class=\"input-group\">\r\n");
      out.write("                                        <input class=\"form-control\" type=\"text\" placeholder=\"E-mail ... \">\r\n");
      out.write("                                        <span class=\"input-group-btn\">\r\n");
      out.write("                                            <button class=\"btn btn-primary subscribe\" type=\"button\"><i class=\"pe-7s-paper-plane pe-2x\"></i></button>\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- /input-group -->\r\n");
      out.write("                                </form> \r\n");
      out.write("\r\n");
      out.write("                                <div class=\"social pull-right\"> \r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a class=\"wow fadeInUp animated\" href=\"https://twitter.com/kimarotec\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("                                        <li><a class=\"wow fadeInUp animated\" href=\"https://www.facebook.com/kimarotec\" data-wow-delay=\"0.2s\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("                                        <li><a class=\"wow fadeInUp animated\" href=\"https://plus.google.com/kimarotec\" data-wow-delay=\"0.3s\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("                                        <li><a class=\"wow fadeInUp animated\" href=\"https://instagram.com/kimarotec\" data-wow-delay=\"0.4s\"><i class=\"fa fa-instagram\"></i></a></li>\r\n");
      out.write("                                        <li><a class=\"wow fadeInUp animated\" href=\"https://instagram.com/kimarotec\" data-wow-delay=\"0.6s\"><i class=\"fa fa-dribbble\"></i></a></li>\r\n");
      out.write("                                    </ul> \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"footer-copy text-center\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"pull-left\">\r\n");
      out.write("                            <span> (C) <a href=\"http://www.KimaroTec.com\">KimaroTheme</a> , All rights reserved 2016  </span> \r\n");
      out.write("                        </div> \r\n");
      out.write("                        <div class=\"bottom-menu pull-right\"> \r\n");
      out.write("                            <ul> \r\n");
      out.write("                                <li><a class=\"wow fadeInUp animated\" href=\"#\" data-wow-delay=\"0.2s\">Home</a></li>\r\n");
      out.write("                                <li><a class=\"wow fadeInUp animated\" href=\"#\" data-wow-delay=\"0.3s\">Property</a></li>\r\n");
      out.write("                                <li><a class=\"wow fadeInUp animated\" href=\"#\" data-wow-delay=\"0.4s\">Faq</a></li>\r\n");
      out.write("                                <li><a class=\"wow fadeInUp animated\" href=\"#\" data-wow-delay=\"0.6s\">Contact</a></li>\r\n");
      out.write("                            </ul> \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<script src=\"/semi/resources/js/modernizr-2.6.2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"/semi/resources/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("        <script src=\"/semi/resources/js/bootstrap-select.min.js\"></script>\r\n");
      out.write("        <script src=\"/semi/resources/js/bootstrap-hover-dropdown.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"/semi/resources/js/easypiechart.min.js\"></script>\r\n");
      out.write("        <script src=\"/semi/resources/js/jquery.easypiechart.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"/semi/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("        <script src=\"/semi/resources/js/wow.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <script src=\"/semi/resources/js/price-range.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"/semi/resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
