/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2018-08-21 11:13:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.notice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import semi.notice.model.vo.Notice;
import java.util.ArrayList;

public final class noticeGongListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/views/notice/../../end.jsp", Long.valueOf(1534838873583L));
    _jspx_dependants.put("/views/notice/../../header.jsp", Long.valueOf(1534842675834L));
    _jspx_dependants.put("/views/notice/../../footer.jsp", Long.valueOf(1534848048461L));
    _jspx_dependants.put("/views/notice/../../head.jsp", Long.valueOf(1534838571126L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("semi.notice.model.vo.Notice");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"noticeGongError.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	ArrayList<Notice> list = (ArrayList<Notice>)request.getAttribute("list");
	int listCount =((Integer)request.getAttribute("listCount")).intValue();
	int startPage = ((Integer)request.getAttribute("startPage")).intValue();
	int endPage = ((Integer)request.getAttribute("endPage")).intValue();
	int maxPage = ((Integer)request.getAttribute("maxPage")).intValue();
	int currentPage = ((Integer)request.getAttribute("currentPage")).intValue();

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	String mName = (String)session.getAttribute("m_Name");
	String mId = (String)session.getAttribute("m_Id");
	String mPassword = (String)session.getAttribute("m_password");


      out.write("\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"description\" content=\"GARO is a real-estate template\">\r\n");
      out.write("<meta name=\"author\" content=\"Kimarotec\">\r\n");
      out.write("<meta name=\"keyword\" content=\"html5, css, bootstrap, property, real-estate theme , bootstrap template\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("<link rel=\"icon\" href=\"favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/normalize.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/fontello.css\">\r\n");
      out.write("<link href=\"/semi/resources/fonts/icon-7-stroke/css/pe-icon-7-stroke.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/semi/resources/fonts/icon-7-stroke/css/helper.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/semi/resources/css/animate.css\" rel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/bootstrap-select.min.css\"> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/icheck.min_all.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/price-range.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/owl.carousel.css\">  \r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/owl.theme.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/owl.transitions.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/lightslider.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/semi/resources/css/responsive.css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/semi/resources/js/jquery/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("<title>09빌려줘</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 바디까지!! -->");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#btnLogin\").click(function(){\r\n");
      out.write("\t\t\t\t\tvar mid = $(\"#mid\").val();\r\n");
      out.write("\t\t\t\t\tvar mpassword = $(\"#mpassword\").val();\r\n");
      out.write("\t\t\t\t\tvar exp = /[a-z0-9]$/;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(mid == \"\"){\r\n");
      out.write("\t\t\t\t\t\talert(\"아이디를 입력해주세요\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#mid\").focus();\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(!exp.test(mid)){\r\n");
      out.write("\t\t\t\t\t\talert(\"영문자와 숫자만 입력가능합니다.\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#mid\").focus();\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t    if (mpassword == \"\") {\r\n");
      out.write("\t\t                alert(\"비밀번호를 입력해주세요\");\r\n");
      out.write("\t\t                $(\"#mpassword\").focus();\r\n");
      out.write("\t\t                return;\r\n");
      out.write("\t\t            }\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction goPage(){\r\n");
      out.write("\t\t\t\tlocation.href = \"/semi/adminIndex.jsp\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("        <style type=\"text/css\">\r\n");
      out.write("        input::placeholder {\r\n");
      out.write("  \t\t\tcolor: #aaaaaa;\r\n");
      out.write("\t\t\tfont-size : 10px;\r\n");
      out.write("\t\t}\r\n");
      out.write("        </style>\r\n");
      out.write("        <!-- Body content -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"header-connect\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-5 col-sm-8  col-xs-12\">\r\n");
      out.write("                        <div class=\"header-half header-call\">\r\n");
      out.write("                            <p>\r\n");
      out.write("                                <span><i class=\"pe-7s-call\"></i> 010-1234-5678</span>\r\n");
      out.write("                                <span><i class=\"pe-7s-mail\"></i> hongildong@iei\t.org</span>\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-2 col-md-offset-5  col-sm-3 col-sm-offset-1  col-xs-12\">\r\n");
      out.write("                        <div class=\"header-half header-social\">\r\n");
      out.write("                            <ul class=\"list-inline\">\r\n");
      out.write("                             \r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>        \r\n");
      out.write("        <!--End top header -->\r\n");
      out.write("\r\n");
      out.write("        <nav class=\"navbar navbar-default \">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("                <div class=\"navbar-header\">\r\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navigation\">\r\n");
      out.write("                        <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("                    <img src=\"/semi/resources/images/common/09.svg\" alt=\"\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("                <div class=\"collapse navbar-collapse yamm\" id=\"navigation\">\r\n");
      out.write("                    <div class=\"button navbar-right\" id=\"ajax_load_indicator\">\r\n");
      out.write("                   \r\n");
      out.write("                        ");
 if(mName == null){ 
      out.write("\r\n");
      out.write("                        <input type=\"button\" id=\"loginradio\" name=\"loginradio\" value=\"관리자로 전환\" onclick=\"goPage();\">\r\n");
      out.write("                        <form action=\"/semi/login\" method=\"post\">\r\n");
      out.write("                        <table width=\"250\" height=\"75\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t\t<tr><td width=\"200\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t  <input type=\"text\"  id=\"mid\" name=\"mid\" size=\"15\" required placeholder=\"아이디를 입력하세요\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"50\" rowspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"로그인\" class= \"navbar-btn nav-button wow bounceInRight login\" id=\"btnLogin\">\r\n");
      out.write("\t\t\t\t\t</td></tr>\r\n");
      out.write("\t\t\t\t<tr><td>\r\n");
      out.write("\t\t\t\t\t<!-- <input type=\"password\" name=\"userpwd\" size=\"15\"> -->\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" id=\"mpassword\" name=\"mpassword\" size=\"15\" required placeholder=\"비밀번호를 입력하세요\">\r\n");
      out.write("\t\t\t\t   </td></tr>\r\n");
      out.write("\t\t\t\t   <tr><td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/semi/views/member/memberEnroll.jsp\">회원가입</a> &nbsp;\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">아이디/암호조회</a>\r\n");
      out.write("\t\t\t\t</td></tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<table width=\"250\" height=\"75\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t<tr><td width=\"150\">\r\n");
      out.write("\t\t\t\t\t");
      out.print( mName );
      out.write(" 님. \r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"100\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/semi/logout\">로그아웃</a>\r\n");
      out.write("\t\t\t\t\t</td></tr>\r\n");
      out.write("\t\t\t\t<tr><td colspan=\"2\">\r\n");
      out.write("\t\t\t\t<a href=\"/semi/myinfo?mid=");
      out.print( mId );
      out.write("\">내 정보보기</a>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</td></tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul class=\"main-nav nav navbar-nav navbar-right\">\r\n");
      out.write("                        <li class=\"wow fadeInDown\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                           <a class=\"\" href=\"/semi/index.jsp\"> Home </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                        <li class=\"dropdown ymm-sw \" data-wow-delay=\"0.2s\">\r\n");
      out.write("                        \t<a href=\"index.html\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\" data-delay=\"200\">대여품목 <b class=\"caret\"></b></a>\r\n");
      out.write("                        \t<ul class=\"dropdown-menu navbar-nav\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"/semi/plist\">전체보기</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"/semi/views/payment/paymentProgressView.jsp\">- 절단공구</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">- 드릴공구</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">- 충전공구</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">- 기타공구</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">- 기타생활공구</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"dropdown ymm-sw \" data-wow-delay=\"0.3s\">\r\n");
      out.write("                        \t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\" data-delay=\"200\">게시판 <b class=\"caret\"></b></a>\r\n");
      out.write("                        \t<ul class=\"dropdown-menu navbar-nav\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"/semi/nglist\">- 공지사항</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"Qna.jsp\">- 문    의</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"reboard.jsp\">- 후    기</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"wow fadeInDown\" data-wow-delay=\"0.4s\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-toggle\">오시는길</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                        <li class=\"wow fadeInDown\" data-wow-delay=\"0.5s\"><a href=\"#\">이용안내</a></li>\r\n");
      out.write("                      \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div><!-- /.navbar-collapse -->\r\n");
      out.write("            </div><!-- /.container-fluid -->\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!-- End of nav bar -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction showNoticeWriteForm(){\r\n");
      out.write("\t\t//글등록 버튼 클릭하면, noticeGongWriteForm.jsp 이동\r\n");
      out.write("\t\tloaction.href = \"/second/gonggu/noticego/noticeGongWriteForm.jsp\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("<br><br><br>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table id=\"table\" align=\"center\" height=\"500\" width=\"650\" cellspacing=\"0\" border=\"1\" >\r\n");
      out.write("<tr>\r\n");
      out.write("\t<th width=\"50\"  style=\"text-align:center;\">번호</th>\r\n");
      out.write("\t<th width=\"400\" style=\"text-align:center;\">제목</th>\r\n");
      out.write("\t<th width=\"70\" style=\"text-align:center;\">작성자</th>\r\n");
      out.write("\t<th width=\"100\" style=\"text-align:center;\">날짜</th>\r\n");
      out.write("\t<th width=\"50\" style=\"text-align:center;\">조회수</th>\r\n");
      out.write("\t<!-- <th>번호</th><th></th><th>작성자</th>\r\n");
      out.write("\t<th>날짜</th><th>조회수</th><th>첨부파일</th> -->\r\n");
      out.write("</tr>\r\n");
 for(Notice n : list){ 
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align=\"center\">");
      out.print( n.getN_no() );
      out.write("</td>\r\n");
      out.write("\t<td >\r\n");
      out.write("\t\t<a href=\"/second/ngdetail?no=");
      out.print( n.getN_no());
      out.write("&page=");
      out.print( currentPage );
      out.write("\">\r\n");
      out.write("\t\t    &nbsp;&nbsp;");
      out.print( n.getN_title() );
      out.write("</a>\r\n");
      out.write("\t\t");
 if(n.getN_file1() != null){ 
      out.write("\r\n");
      out.write("\t\t<img style= \"width:10px; height:10px;\" src=\"/second/image/disk.png\">\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("\t</td>\r\n");
      out.write("\t<td align=\"center\">");
      out.print( n.getA_id() );
      out.write("</td>\r\n");
      out.write("\t<td align=\"center\">");
      out.print( n.getN_date() );
      out.write("</td>\r\n");
      out.write("\t<td align=\"center\">");
      out.print( n.getN_count() );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
 } 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<!-- 페이징처리 -->\r\n");
      out.write("<div style=\"text-align: center;\">\r\n");
 if(currentPage <= 1){ 
      out.write("\r\n");
      out.write("\t[맨처음]&nbsp;\r\n");
 }else{ 
      out.write("\r\n");
      out.write("\t<a href=\"/second/nglist?page=1\">[맨처음]</a>\r\n");
 } 
      out.write('\r');
      out.write('\n');
 if((currentPage - 10) < startPage &&
		(currentPage - 10) > 1){ 
      out.write("\r\n");
      out.write("\t\t<a href = \"/second/nglist?page=");
      out.print( startPage - 10 );
      out.write("\">[이전]</a>\t\t\r\n");
 }else{ 
      out.write("\r\n");
      out.write("\t[이전]&nbsp;\r\n");
 } 
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
 for(int p = startPage; p <= endPage; p++){
		if(p == currentPage){

      out.write("\r\n");
      out.write("\t<font color=\"red\" size=\"4\">[");
      out.print( p );
      out.write("]</font>\r\n");
 } else{ 
      out.write("\r\n");
      out.write("\t<a href=\"/second/nglist?page=");
      out.print( p );
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</a>\r\n");
 }} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 if((currentPage + 10) > endPage &&
		(currentPage + 10) < maxPage){ 
      out.write("\r\n");
      out.write("\t<a href=\"/second/nglist?page=");
      out.print( endPage + 10 );
      out.write("\">[다음]</a>\r\n");
 }else{ 
      out.write("\r\n");
      out.write("\t[다음]&nbsp;\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
 if(currentPage >= maxPage){ 
      out.write("\r\n");
      out.write("\t[맨끝]&nbsp;\r\n");
 }else{ 
      out.write("\r\n");
      out.write("\t<a href=\"/second/nglist?page=");
      out.print( maxPage );
      out.write("\"></a>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div  style=\"position: absolute; left: 1200px; top: 930px; \">\r\n");
      out.write("\r\n");
      out.write("\t<button  id=\"writeBtn\" onclick=\"moveWritePage();\">\r\n");
      out.write("\t<a href = \"/second/gonggu/noticego/noticeGongWriteForm.jsp\">\r\n");
      out.write("\t공지글 등록</a></button>\r\n");
      out.write("</div>\r\n");
      out.write("<br><br><br><br><br><br><br><br><br><br>\r\n");
      out.write("\r\n");
      out.write("w\r\n");
      out.write("\r\n");
      out.write("        <!-- Footer area-->\r\n");
      out.write("        <div class=\"footer-area\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\" footer\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-md-3 col-sm-6 wow fadeInRight animated\">\r\n");
      out.write("                            <div class=\"single-footer\">\r\n");
      out.write("                                <h4>About us </h4>\r\n");
      out.write("                                <div class=\"footer-title-line\"></div>\r\n");
      out.write("\r\n");
      out.write("                                <img src=\"/semi/assets/img/footer-logo.png\" alt=\"\" class=\"wow pulse\" data-wow-delay=\"1s\">\r\n");
      out.write("                                <p>Lorem ipsum dolor cum necessitatibus su quisquam molestias. Vel unde, blanditiis.</p>\r\n");
      out.write("                                <ul class=\"footer-adress\">\r\n");
      out.write("                                    <li><i class=\"pe-7s-map-marker strong\"> </i> 9089 your adress her</li>\r\n");
      out.write("                                    <li><i class=\"pe-7s-mail strong\"> </i> email@yourcompany.com</li>\r\n");
      out.write("                                    <li><i class=\"pe-7s-call strong\"> </i> +1 908 967 5906</li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3 col-sm-6 wow fadeInRight animated\">\r\n");
      out.write("                            <div class=\"single-footer\">\r\n");
      out.write("                                <h4>Quick links </h4>\r\n");
      out.write("                                <div class=\"footer-title-line\"></div>\r\n");
      out.write("                                <ul class=\"footer-menu\">\r\n");
      out.write("                                    <li><a href=\"properties.html\">Properties</a>  </li> \r\n");
      out.write("                                    <li><a href=\"#\">Services</a>  </li> \r\n");
      out.write("                                    <li><a href=\"submit-property.html\">Submit property </a></li> \r\n");
      out.write("                                    <li><a href=\"contact.html\">Contact us</a></li> \r\n");
      out.write("                                    <li><a href=\"faq.html\">fqa</a>  </li> \r\n");
      out.write("                                    <li><a href=\"faq.html\">Terms </a>  </li> \r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3 col-sm-6 wow fadeInRight animated\">\r\n");
      out.write("                            <div class=\"single-footer\">\r\n");
      out.write("                                <h4>Last News</h4>\r\n");
      out.write("                                <div class=\"footer-title-line\"></div>\r\n");
      out.write("                                <ul class=\"footer-blog\">\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"col-md-3 col-sm-4 col-xs-4 blg-thumb p0\">\r\n");
      out.write("                                            <a href=\"single.html\">\r\n");
      out.write("                                                <img src=\"assets/img/demo/small-proerty-2.jpg\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <span class=\"blg-date\">12-12-2016</span>\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-8  col-sm-8 col-xs-8  blg-entry\">\r\n");
      out.write("                                            <h6> <a href=\"single.html\">Add news functions </a></h6> \r\n");
      out.write("                                            <p style=\"line-height: 17px; padding: 8px 2px;\">Lorem ipsum dolor sit amet, nulla ...</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li> \r\n");
      out.write("\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"col-md-3 col-sm-4 col-xs-4 blg-thumb p0\">\r\n");
      out.write("                                            <a href=\"single.html\">\r\n");
      out.write("                                                <img src=\"/semi/assets/img/demo/small-proerty-2.jpg\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <span class=\"blg-date\">12-12-2016</span>\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-8  col-sm-8 col-xs-8  blg-entry\">\r\n");
      out.write("                                            <h6> <a href=\"/semi/single.html\">Add news functions </a></h6> \r\n");
      out.write("                                            <p style=\"line-height: 17px; padding: 8px 2px;\">Lorem ipsum dolor sit amet, nulla ...</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li> \r\n");
      out.write("\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"col-md-3 col-sm-4 col-xs-4 blg-thumb p0\">\r\n");
      out.write("                                            <a href=\"single.html\">\r\n");
      out.write("                                                <img src=\"/semi/assets/img/demo/small-proerty-2.jpg\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <span class=\"blg-date\">12-12-2016</span>\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-8  col-sm-8 col-xs-8  blg-entry\">\r\n");
      out.write("                                            <h6> <a href=\"single.html\">Add news functions </a></h6> \r\n");
      out.write("                                            <p style=\"line-height: 17px; padding: 8px 2px;\">Lorem ipsum dolor sit amet, nulla ...</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3 col-sm-6 wow fadeInRight animated\">\r\n");
      out.write("                            <div class=\"single-footer news-letter\">\r\n");
      out.write("                                <h4>Stay in touch</h4>\r\n");
      out.write("                                <div class=\"footer-title-line\"></div>\r\n");
      out.write("                                <p>Lorem ipsum dolor sit amet, nulla  suscipit similique quisquam molestias. Vel unde, blanditiis.</p>\r\n");
      out.write("\r\n");
      out.write("                                <form>\r\n");
      out.write("                                    <div class=\"input-group\">\r\n");
      out.write("                                        <input class=\"form-control\" type=\"text\" placeholder=\"E-mail ... \">\r\n");
      out.write("                                        <span class=\"input-group-btn\">\r\n");
      out.write("                                            <button class=\"btn btn-primary subscribe\" type=\"button\"><i class=\"pe-7s-paper-plane pe-2x\"></i></button>\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- /input-group -->\r\n");
      out.write("                                </form> \r\n");
      out.write("\r\n");
      out.write("                                <div class=\"social pull-right\"> \r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a class=\"wow fadeInUp animated\" href=\"https://twitter.com/kimarotec\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("                                        <li><a class=\"wow fadeInUp animated\" href=\"https://www.facebook.com/kimarotec\" data-wow-delay=\"0.2s\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("                                        <li><a class=\"wow fadeInUp animated\" href=\"https://plus.google.com/kimarotec\" data-wow-delay=\"0.3s\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("                                        <li><a class=\"wow fadeInUp animated\" href=\"https://instagram.com/kimarotec\" data-wow-delay=\"0.4s\"><i class=\"fa fa-instagram\"></i></a></li>\r\n");
      out.write("                                        <li><a class=\"wow fadeInUp animated\" href=\"https://instagram.com/kimarotec\" data-wow-delay=\"0.6s\"><i class=\"fa fa-dribbble\"></i></a></li>\r\n");
      out.write("                                    </ul> \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"footer-copy text-center\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"pull-left\">\r\n");
      out.write("                            <span> (C) <a href=\"http://www.KimaroTec.com\">KimaroTheme</a> , All rights reserved 2016  </span> \r\n");
      out.write("                        </div> \r\n");
      out.write("                        <div class=\"bottom-menu pull-right\"> \r\n");
      out.write("                            <ul> \r\n");
      out.write("                                <li><a class=\"wow fadeInUp animated\" href=\"#\" data-wow-delay=\"0.2s\">Home</a></li>\r\n");
      out.write("                                <li><a class=\"wow fadeInUp animated\" href=\"#\" data-wow-delay=\"0.3s\">Property</a></li>\r\n");
      out.write("                                <li><a class=\"wow fadeInUp animated\" href=\"#\" data-wow-delay=\"0.4s\">Faq</a></li>\r\n");
      out.write("                                <li><a class=\"wow fadeInUp animated\" href=\"#\" data-wow-delay=\"0.6s\">Contact</a></li>\r\n");
      out.write("                            </ul> \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("        <script src=\"/semi/resources/js/modernizr-2.6.2.min.js\"></script>\r\n");
      out.write("       \r\n");
      out.write("        <script src=\"/semi/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("        <script src=\"/semi/resources/js/bootstrap-select.min.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        <script src=\"/semi/resources/js/icheck.min.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        <script src=\"/semi/resources/js/bootstrap-hover-dropdown.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"/semi/resources/js/easypiechart.min.js\"></script>\r\n");
      out.write("        <script src=\"/semi/resources/js/jquery.easypiechart.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"/semi/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("        <script src=\"/semi/resources/js/wow.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script type=\"text/javascript\" src=\"/semi/resources/js/lightslider.min.js\"></script>\r\n");
      out.write("        <script src=\"/semi/resources/js/price-range.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"/semi/resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
